language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: YWOU+1aJwCxzIKNRsqpS7x5eUG5+cEWJAaBtxwLEve8GnkAVagYQt1ofOSK/kjStxJTW7JwTBPbhtlOnNYceDf4y81/b5NEroQfd59uqHY9auCVwgpRCwhMQXY1DOD7aYXtov8QBb108Mvlx3iVJJZN09TeT/+hwORLtTetE4K/JJvWaCVwB9YthWPNwkjQAt5tHzmrKD4PDGgEfmmfa16fRPe/ll07YhMoPSXIHc1Igt0UaNchW8e9xKsnrnEut0Opa6ig/p+FaeEpfF06hsc5YlCIjW2OAbZl2AX2mH6KTHDWHnj4V57dvtUKt/NlUUDjOv7AOAlO1p0gdKctC3qCxuw6kpO5WK2GY+LL1VNpb28RokZrUMjPYrgGRIDo+oIKvPE6zjSdXAKgdvCfFn5QAbwIPlyfNjR1uVCojA7bk/7Joi1Uc25frrHafS6ZHfzD5dk/0izprbIHcSj6Z6cZ021oZbQawTYh8OmrcMxS5a8nzyL2jakOL/ILIyINqDYiMSd9kRF0zZw7x5JQDYKut3l9Q9ToMTT9Cd90px8ONRSC6X5MDLm2uROygIRW6LR81D9zYTcalA3jlbadZQm08Q8fTqHz0EVRxSCixgLrvdnq7ESLCgCn5xNNrGTzKuXTuLv8RKltVY4OOjFVCZ/BRrXxYH45cERwVJcai35o=
  app: whats-new-deployment
  skip_cleanup: true