language: node_js
node_js:
- node
notifications:
  email: false
deploy:
provider: heroku
  api_key:
    secure: Vfp7uAuUhzf4/LMOlEcMV9WtelURK6OejPG4GFp/jH/X9X8iSNt32KM6ubXCw9b7n5QO6qeBjkC73/XvTVr2+VGIvzatmOG/2dOhFuHS5+mgLRKnI9lO1uxNatvl87xvKexxYK+0QseY4A3i01gEIz/VmXdHK5Kypvg7KEUvfypQjwn+flGL9h6PLRcmf41p64SiFWgDCt88e73UmPgNzYnrPR+qcI1ujHcYPTqNtBPGDq1424FO0lTku9jAeH7NqPpFDrkoh72Yr2eAZ5DycSXxi8SaWaNXm+79/WcRDvTZTbYTTvdK/YiWbFIO5mSIL57P1EDMeyBVZ/MlmKIsgquX9ZG5sFSdLWHXH1D/LeKR5m9GTGZEq/DBdZ0Rhm9j9B1ZWRsevDBRPOMcxmWksFbQJR2F+hImIRBFqx9cZrj3lF0pXBYr2kmJ5gd0qW59OD5yvZe5G4HKDlz/bB49/X3Q80u1f4d9o4ppLNg0+YIrBpmchlLpaotqULiSgvzmsMgfqHvtUNcHkwjOFrBUtCFA2JZCZmlRrh1EYOJMR/DNrfizAtDsFRFfv7WjDNdLoXKjTpPYSXIaPc+pX5O2R4BqambWSFZyJ5o3+bJfc1bq6RrnxglUY0JTg3kns5f31WLfW0MeJ/Jsthi+19SqlfC5uZVJNr6bAygJQ3zqdys=
  app: whats-new-deployment
  skip_cleanup: true
